### ISSUE TITLE
data.zip

### ISSUE THREAD

**Issue by henryatintel** [Becomebright/GroundVQA#1]
Hi,

Like the work!

I an wondering if the data will be released like the annotations?

Another question: in the code, each item from the dataloader has only 1 question paired with a video for the NLQ task (before batching). Does the codebase supports grounding multiple questions within a video? Thanks.

**Comment by Becomebright** [comment]
Thanks for your questions.

A1: The data has already been released on [Huggingface](https://huggingface.co/Becomebright/GroundVQA/blob/main/data.zip).
A2: Grounding multiple questions is not supported.
