### ISSUE TITLE
Question about providing model checkpoint

### ISSUE THREAD

**Issue by soyeonhong** [Becomebright/GroundVQA#2]
Hello, I'd like to ask if the following checkpoints can be provided:

1. GroundVQA base checkpoint pretrained using only NLQv2 **without NaQ** (**video features used: EgoVLP and InternVideo)**
2. GroundVQA base checkpoint pretrained using only NLQv2 **without NaQ** (**video features used: only EgoVLP)**

**Comment by Becomebright** [comment]
Sorry for the delayed reply. I've been quite busy recently.

The checkpoints have been uploaded to Huggingface:
- [GroundVQA_B-NLQ-VLG-val_R1_03=15.5.ckpt](https://huggingface.co/Becomebright/GroundVQA/blob/main/GroundVQA_B-NLQ-VLG-val_R1_03%3D15.5.ckpt)
- [GroundVQA_B-NLQ-VLG-EgoVLP-val_R1_03=13.0.ckpt](https://huggingface.co/Becomebright/GroundVQA/blob/main/GroundVQA_B-NLQ-VLG-EgoVLP-val_R1_03%3D13.0.ckpt)

Thank you for your patience.

**Comment by soyeonhong** [comment]
Thank you so much for your reply despite your busy schedule! Thanks to you, it helped me a lot!
