### ISSUE TITLE
LayerNorm class duplicate

### ISSUE THREAD

**Issue by leon-herbrik** [Becomebright/GroundVQA#5]
https://github.com/Becomebright/GroundVQA/blame/de7c1c663c315f9edaa576755fa850f1d66bdd9b/model/ours/nlq_head.py#L326

Hey there,

just noticed that the LayerNorm class appears twice in the code.
Once in line 326 and once in line 9 :)

**Comment by Becomebright** [comment]
Thanks a lot for pointing this out. It's fixed: https://github.com/Becomebright/GroundVQA/commit/7aceb17d1a7dab126e46335a8c5f0dbfa454c111.
