### ISSUE TITLE
Training on Ego4D NLQ.

### ISSUE THREAD

**Issue by leon-herbrik** [Becomebright/GroundVQA#6]
Hello,

first of all, amazing work!

I have two questions about the method:
  1. Is it supported to train the model on only the Ego4D NLQ data?
  2. Does the 'annotations.NLQ_train.json' file contain the additional questions you generated with Llama2?
 
Thank you!

**Comment by Becomebright** [comment]
1. Yes, I've uploaded the [training](https://github.com/Becomebright/GroundVQA/blob/main/scripts/train_groundvqa_b-nlq.sh) and [evaluation](https://github.com/Becomebright/GroundVQA/blob/main/scripts/evaluate_groundvqa_b-nlq.sh) scripts. You can also find the checkpoints at https://github.com/Becomebright/GroundVQA/issues/2.
2. No, `annotations.NLQ_train.json` only contains the training set from NLQv2. The generated samples are in `annotations.EgoTimeQA.json`.

Let me know if you need any further clarification!

**Comment by leon-herbrik** [comment]
Got it, thanks a lot :)
